/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dreamco;

import static dreamco.UserFrame.updatePendingFile;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Jeremiah
 */
public class AdminRegistrationFrame extends javax.swing.JFrame {


    private static String newfullname;
    private static String newpassword, confirmpassword;
    
    
    
    public AdminRegistrationFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        namefield = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        newpasswordfield = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        confirmpasswordfield = new javax.swing.JPasswordField();
        checkboxtc = new javax.swing.JCheckBox();
        cancelbutton = new javax.swing.JButton();
        registrationbutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        namefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namefieldActionPerformed(evt);
            }
        });
        jPanel1.add(namefield);
        namefield.setBounds(200, 60, 260, 40);

        jLabel6.setBackground(new java.awt.Color(102, 102, 102));
        jLabel6.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Enter Full Name");
        jLabel6.setToolTipText("This will be your username when logging in");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(50, 60, 150, 40);

        jLabel9.setBackground(new java.awt.Color(102, 102, 102));
        jLabel9.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("New Password");
        jLabel9.setToolTipText("make sure your password is secure but easy to  remember as well!");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(50, 110, 150, 40);
        jPanel1.add(newpasswordfield);
        newpasswordfield.setBounds(200, 110, 260, 40);

        jLabel7.setBackground(new java.awt.Color(102, 102, 102));
        jLabel7.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Confirm Password");
        jLabel7.setToolTipText("make sure your password is secure but easy to  remember as well!");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(50, 160, 150, 40);
        jPanel1.add(confirmpasswordfield);
        confirmpasswordfield.setBounds(200, 160, 260, 40);

        checkboxtc.setBackground(new java.awt.Color(117, 230, 218));
        checkboxtc.setForeground(new java.awt.Color(255, 255, 255));
        checkboxtc.setText("Agree to terms and conditions");
        checkboxtc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxtcActionPerformed(evt);
            }
        });
        jPanel1.add(checkboxtc);
        checkboxtc.setBounds(50, 210, 200, 30);

        cancelbutton.setText("Cancel");
        cancelbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(cancelbutton);
        cancelbutton.setBounds(370, 210, 90, 25);

        registrationbutton.setBackground(new java.awt.Color(24, 154, 180));
        registrationbutton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        registrationbutton.setForeground(new java.awt.Color(255, 255, 255));
        registrationbutton.setText("Register User and get that bread!");
        registrationbutton.setVisible(false);
        registrationbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrationbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(registrationbutton);
        registrationbutton.setBounds(120, 270, 280, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 989, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 758, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void namefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namefieldActionPerformed
 
    }//GEN-LAST:event_namefieldActionPerformed

    private void checkboxtcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkboxtcActionPerformed
        if(checkboxtc.isSelected()){
        registrationbutton.setVisible(true);
        JOptionPane.showMessageDialog(null, "You agree to the collection of a one-off payment of RM50 to register as a member of DreamCo. A membership card will given upon registration.", "  Terms & Conditions", JOptionPane.INFORMATION_MESSAGE);
        }
        else{
        registrationbutton.setVisible(false);
        }
    }//GEN-LAST:event_checkboxtcActionPerformed

    private void cancelbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelbuttonActionPerformed

    }//GEN-LAST:event_cancelbuttonActionPerformed

    private void registrationbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrationbuttonActionPerformed
        int key=25;
        newfullname=namefield.getText();
        newpassword=newpasswordfield.getText();
        confirmpassword=confirmpasswordfield.getText();
            MyTree t = new MyTree();
            t.addUser();
           // String zero = String.valueOf(0);
            
        try {
            //t.a
            t.add(newfullname, newpassword, String.valueOf(0));
            t.appendUserClearFile();
            
            //MyTree.setIDCounter(MyTree.getIDCounter()+1);
        
//        try {
//            updatePendingFile(newfullname, newpassword);
//        } catch (IOException ex) {
//            JOptionPane.showMessageDialog(null, "Pending File Not Found!", " System Error", JOptionPane.ERROR_MESSAGE);
//        }
//        newfullname="";
//        newpassword="";
//        confirmpassword="";
        } catch (IOException ex) {
            Logger.getLogger(AdminRegistrationFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    
        JOptionPane.showMessageDialog(null, "Thank-you for registering. Your registration request is pending and will be approved by an admin in 2-3 business days.", "  Registration Request Sent", JOptionPane.INFORMATION_MESSAGE);  
    }//GEN-LAST:event_registrationbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void runAdminRegistrationFrame() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminRegistrationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminRegistrationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminRegistrationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminRegistrationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminRegistrationFrame().setVisible(true);
            }
        });
    }
    
    
    /////////////////////////////////////////////////////////////////// Method to write encrypted string from registration to PENDING file //////////////////////////////
    public static void updatePendingFile(String name, String password) throws IOException{
        BufferedWriter bw=new BufferedWriter(new FileWriter(new File("Userdata.txt"),true));
        bw.write(String.valueOf(MyTree.getIDCounter()));
        bw.write("\n"+ newpassword);
        bw.write("\n"+ 0);    //0    
        bw.write("\n" + newfullname);
        bw.write("\n" + String.valueOf(0));
        bw.close();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelbutton;
    private javax.swing.JCheckBox checkboxtc;
    private javax.swing.JPasswordField confirmpasswordfield;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField namefield;
    private javax.swing.JPasswordField newpasswordfield;
    private javax.swing.JButton registrationbutton;
    // End of variables declaration//GEN-END:variables
}
